# Header
menu:
  Home: /
  Archives: /archives
  About: /about

#Profile
profile:
  social:
    github: https://github.com/buhuo00
    zhihu: https://www.zhihu.com/people/liu-deng-42-20/activities
    email: 1054576070@qq.com

#site 
site:
  description: javascript，html，css
  keywords: javascript,css,烬王的技术博客
  favicon: /favicon.png
  
#Comment
disqus_shortname: #fencer-1 #disqus
livere: MTAyMC8zMjQ1MS85MDEy 

#RSS
rss: atom.xml

# Version
version: 2.0.0

